Link validator
DFE-Digital/get-into-teaching-app pull request #589
Opened 2020-11-23 15:56 UTC by peteryates

### Trello card

N/A

### Context

We had a few broken/malformed links knocking around our content repo but finding them manually is difficult.

### Changes proposed in this pull request

Add some specs that ensure the internal links are valid. We're not checking external ones because a site that's down could affect our build.

The link checker is only interested in internal links and anchors, it specifically ignores:

* any link that starts with http (external)
* any telephone or email links
* links to any events pages (which call external APIs)
* links to the privacy policy page (again, external API)
* links that trigger JavaScript actions

It's disabled by default but now there's a new step in the workflow that runs the just the specs tagged with `link_checks`, or it can be run manually via `be rspec --tag link_checks`

### Guidance to review

Sensible approach?

2020-11-23 16:34 UTC, peteryates commented
Wait a minute! The content's not there in CI 🤦🏽‍♂️ 

```
Run docker run -t --rm -e RAILS_ENV=test dfedigital/get-into-teaching-web:sha-03ceb60 \
  docker run -t --rm -e RAILS_ENV=test dfedigital/get-into-teaching-web:sha-03ceb60 \
    rspec --format documentation --tag link_checks
  shell: /bin/bash -e {0}
  env:
    APP_REPOSITORY: dfedigital/get-into-teaching-web
    CONTENT_REPOSITORY: DFE-Digital/get-into-teaching-content
Run options: include {:link_checks=>true}

All examples were filtered out

Finished in 0.00102 seconds (files took 2.3 seconds to load)
0 examples, 0 failures

```

2020-11-25 11:23 UTC, jebw requested changes
LGTM but minor changes recommended to naming

2020-11-25 11:23 UTC, jebw commented on spec/features/content_pages_spec.rb
> +      specify "the anchor links reference existing IDs", content: true do
Can these use `scenario` for consistency

2020-11-25 11:23 UTC, jebw commented on spec/features/content_pages_spec.rb
> +    describe url do
Can this be more descriptive - ie `"checking #{url}"`

2020-11-25 11:23 UTC, jebw commented on spec/features/content_pages_spec.rb
> +      scenario "visiting #{url}", content: true do
Can this be renamed to to avoid the double reference in an error (`describe` and `scenario` will both list the URL) - eg `responds with success`

2020-11-25 11:50 UTC, jebw approved these changes
LGTM

2020-11-25 14:02 UTC, jebw approved these changes
LGTM

2020-11-25 14:15 UTC, merged